name: quick_blue_simplify
description: A new Flutter project.
version: 0.0.6
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  plugin_platform_interface: ^2.0.2
  mutex: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.quick_blue_simplify
        pluginClass: QuickBluePlugin
      ios:
        pluginClass: QuickBluePlugin
